spring:
  datasource:
    username: root
#    username: admin
#    password: Zsw990807@@00
    password: 123456
#    url: jdbc:mysql://47.106.159.165:3306/handy?useUnicode=true&serverTimezone=UTC&characterEncoding=UTF-8
    url: jdbc:mysql://localhost:3306/xq?useUnicode=true&serverTimezone=UTC&characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource

    initialSize: 5
    minIdle: 5
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    filters: stat,wall
    maxPoolPreparedStatementPerConnectionSize: 20
    useGlobalDataSourceStat: true
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500
  redis:
    host: 47.106.159.165
    port: 6379
jwt:
  access:
    secret: accesstokensecret



mybatis:
  configuration:
    map-underscore-to-camel-case: true

management:
  endpoints:
    web:
      exposure:
        include: shutdown

  endpoint:
    shutdown:
      enabled: true